# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jtlFireGuard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  # Pods for jtlFireGuard

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport', 
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', 
    'RCTAnimation'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNSound', :podspec => '../node_modules/react-native-sound/RNSound.podspec'
  pod 'react-native-baidu-map', :podspec => '../node_modules/react-native-baidu-map/ios/react-native-baidu-map.podspec'
  pod 'react-native-image-picker', path: '../node_modules/react-native-image-picker'
  pod 'react-native-camera', path: '../node_modules/react-native-camera'

  pod 'UMCCommon'
  pod 'UMCPush'
  pod 'UMCSecurityPlugins'
  
  target 'jtlFireGuard-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'jtlFireGuardTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == "React"
          target.remove_from_project
      end
      if target.name == "yoga"
          target.remove_from_project
      end
  end
end
