export default ({
    0:'设备类别（全部）',
    1:'点型感烟火灾探测器',
    2:'点型感温火灾探测器',
    3:'用户信息传输装置',
    4:'可燃气体探测器',
    5:'消火栓按钮',
    6:'手动火灾报警按钮',
    7:'火灾声光警报器',
    8:'火灾光警报器',
    9:'区域显示器（火灾显示盘）',
    10:'火灾报警控制器',
    11:'输入/输出模块',
    12:'输入模块',
    13:'输出模块',
    14:'模块箱',
    15:'手动控制盘',
    16:'中继模块',
    17:'智能压力传感器',
    18:'智能液位传感器',
    19:'智慧消火栓',
    20:'剩余电流式电气火灾监控探测器',
    21:'测温式电气火灾监控探测器',
    22:'剩余电流及测温式电气火灾监控探测器',
    23:'故障电弧探测器',
    24:'独立式电气火灾监控探测器',
    25:'电气火灾监控设备',
    26:'无线独立式光电感烟火灾探测报警器',
    27:'无线可燃气体探测器',
    28:'无线手动火灾报警按钮',
    29:'无线火灾声光警报器',
    30:'人员离岗监测摄像头',
    31:'消防通道堵塞摄像头',
    32:'火焰识别检测摄像头',
    33:'安防摄像头',
    34:'电动闭门器',
    35:'门磁开关',
    36:'防火门监控器',
    37:'电压信号传感器0401',
    38:'电流信号传感器0402',
    39:'电压/电流信号传感器0402/0404',
    40:'消防设备电源状态监控器',
    41:'智慧安全用电监控器',
    42:'智慧安全用电在线监测装置',
    43:'多功能仪表',
    44:'电动车充电桩',
    45:'点型可燃气体探测器',
    46:'独立式可燃气体探测器',
    47:'线型可燃气体探测器',
    48:'探测回路',
    49:'火灾探测器',
    50:'点型感温火灾探测器',
    51:'点型感温火灾探测器(s型)',
    52:'点型感温火灾探测器(R型)',
    53:'线型感温火灾探测器',
    54:'线型感温火灾探测器(s型)',
    55:'线型感温火灾探测器(R型)',
    56:'光纤感温火灾探测器',
    57:'光纤感温火灾探测器',
    58:'点型光电感烟火灾探测器',
    59:'线型光束感烟火灾探测器',
    60:'吸气式感烟火灾探测器',
    61:'线型光束感烟火灾探测器',
    62:'复合式火灾探测器',
    63:'复合式感烟感温火灾探测器',
    64:" 复合式感光感温火灾探浏器",
    65:" 复合式感光感烟火灾探测器",
    66:" 紫外火焰探测器",
    67:" 红外火焰探测器",
    68:" 感光火灾探测器",
    69:" 气体探测器",
    70:" 图像摄像方式火灾探测器",
    71:" 感声火灾探测器",
    72:" 气体灭火控制器",
    73:" 消防电气控制装置",
    74:" 消防控制室图形显示装置",
    75:" 消防水泵",
    76:" 消防水箱",
    77:" 喷淋泵",
    78:" 水流指示器",
    79:" 信号阀",
    80:" 报警阀",
    81:" 压力开关",
    82:" 阀驱动装置",
    83:" 防火门",
    84:" 防火阀",
    85:" 通风空调",
    86:" 泡沫液泵",
    87:" 管网电磁阀",
    88:" 防烟排烟风机",
    89:" 排烟防火阀",
    90:" 常闭送风口",
    91:" 排烟口",
    92:" 电控挡烟垂壁",
    93:" 防火卷帘控制器",
    94:" 防火门监控器",
    95:" 警报装置",
    96:"无线输出模块",
    97:"无线输入模块",
    98:"无线输入/输出模块",
    99:"联动摄像头",

})

// {"data":[{"id":3278,"value":"1","label":"点型感烟火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3279,"value":"2","label":"点型感温火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3280,"value":"3","label":"用户信息传输装置","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3281,"value":"4","label":"可燃气体探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3282,"value":"5","label":"消火栓按钮","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3283,"value":"6","label":"手动火灾报警按钮","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3284,"value":"7","label":"火灾声光警报器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3285,"value":"8","label":"火灾光警报器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3286,"value":"9","label":"区域显示器（火灾显示盘）","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3287,"value":"10","label":"火灾报警控制器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3288,"value":"11","label":"输入/输出模块","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3289,"value":"12","label":"输入模块","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3290,"value":"13","label":"输出模块","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3291,"value":"14","label":"模块箱","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3292,"value":"15","label":"手动控制盘","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3293,"value":"16","label":"中继模块","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3339,"value":"17","label":"智能压力传感器","type":"device_type","parentId":"3261","level":"2","icon":null,"description":null},
// {"id":3340,"value":"18","label":"智能液位传感器","type":"device_type","parentId":"3261","level":"2","icon":null,"description":null},
// {"id":3341,"value":"19","label":"智慧消火栓","type":"device_type","parentId":"3261","level":"2","icon":null,"description":null},
// {"id":3342,"value":"20","label":"剩余电流式电气火灾监控探测器","type":"device_type","parentId":"3262","level":"2","icon":null,"description":null},
// {"id":3343,"value":"21","label":"测温式电气火灾监控探测器","type":"device_type","parentId":"3262","level":"2","icon":null,"description":null},
// {"id":3344,"value":"22","label":"剩余电流及测温式电气火灾监控探测器","type":"device_type","parentId":"3262","level":"2","icon":null,"description":null},
// {"id":3361,"value":"23","label":"故障电弧探测器","type":"device_type","parentId":"3262","level":"2","icon":null,"description":null},
// {"id":3362,"value":"24","label":"独立式电气火灾监控探测器","type":"device_type","parentId":"3262","level":"2","icon":null,"description":null},
// {"id":3363,"value":"25","label":"电气火灾监控设备","type":"device_type","parentId":"3262","level":"2","icon":null,"description":null},
// {"id":3364,"value":"26","label":"无线独立式光电感烟火灾探测报警器","type":"device_type","parentId":"3263","level":"2","icon":null,"description":null},
// {"id":3365,"value":"27","label":"无线可燃气体探测器","type":"device_type","parentId":"3263","level":"2","icon":null,"description":null},
// {"id":3366,"value":"28","label":"无线手动火灾报警按钮","type":"device_type","parentId":"3263","level":"2","icon":null,"description":null},
// {"id":3367,"value":"29","label":"无线火灾声光警报器","type":"device_type","parentId":"3263","level":"2","icon":null,"description":null},
// {"id":3368,"value":"30","label":"人员离岗监测摄像头","type":"device_type","parentId":"3264","level":"2","icon":null,"description":null},
// {"id":3369,"value":"31","label":"消防通道堵塞摄像头","type":"device_type","parentId":"3264","level":"2","icon":null,"description":null},
// {"id":3370,"value":"32","label":"火焰识别检测摄像头","type":"device_type","parentId":"3264","level":"2","icon":null,"description":null},
// {"id":3371,"value":"33","label":"安防摄像头","type":"device_type","parentId":"3264","level":"2","icon":null,"description":null},
// {"id":3372,"value":"34","label":"电动闭门器","type":"device_type","parentId":"3265","level":"2","icon":null,"description":null},
// {"id":3373,"value":"35","label":"门磁开关","type":"device_type","parentId":"3265","level":"2","icon":null,"description":null},
// {"id":3374,"value":"36","label":"防火门监控器","type":"device_type","parentId":"3265","level":"2","icon":null,"description":null},
// {"id":3375,"value":"37","label":"电压信号传感器","type":"device_type","parentId":"3266","level":"2","icon":null,"description":null},
// {"id":3376,"value":"38","label":"电流信号传感器","type":"device_type","parentId":"3266","level":"2","icon":null,"description":null},
// {"id":3377,"value":"39","label":"电压/电流信号传感器","type":"device_type","parentId":"3266","level":"2","icon":null,"description":null},
// {"id":3378,"value":"40","label":"消防设备电源状态监控器","type":"device_type","parentId":"3266","level":"2","icon":null,"description":null},
// {"id":3379,"value":"41","label":"智慧安全用电监控器","type":"device_type","parentId":"3267","level":"2","icon":null,"description":null},
// {"id":3380,"value":"42","label":"智慧安全用电在线监测装置","type":"device_type","parentId":"3267","level":"2","icon":null,"description":null},
// {"id":3381,"value":"43","label":"多功能仪表","type":"device_type","parentId":"3267","level":"2","icon":null,"description":null},
// {"id":3382,"value":"44","label":"电动车充电桩","type":"device_type","parentId":"3268","level":"2","icon":null,"description":null},
// {"id":3424,"value":"0","label":"设备类别(全部)","type":"device_type","parentId":"0","level":"2","icon":null,"description":null},
// {"id":3426,"value":"45","label":"点型可燃气体探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3427,"value":"46","label":"独立式可燃气体探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3428,"value":"47","label":" 线型可燃气体探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3429,"value":"48","label":" 探测回路","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3430,"value":"49","label":" 火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3431,"value":"50","label":"点型感温火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3432,"value":"51","label":" 点型感温火灾探测器(s型)","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3433,"value":"52","label":" 点型感温火灾探测器(R型)","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3434,"value":"53","label":" 线型感温火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3435,"value":"54","label":" 线型感温火灾探测器(S型)","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3436,"value":"55","label":" 线型感温火灾探测器(R型)","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3437,"value":"56","label":" 光纤感温火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3438,"value":"57","label":" 光纤感温火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3439,"value":"58","label":" 点型光电感烟火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3440,"value":"59","label":" 线型光束感烟火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3441,"value":"60","label":" 吸气式感烟火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3442,"value":"59","label":" 线型光束感烟火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3443,"value":"61","label":" 复合式火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3444,"value":"62","label":" 复合式感烟感温火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3445,"value":"63","label":" 复合式感光感温火灾探浏器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3446,"value":"64","label":" 复合式感光感烟火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3447,"value":"65","label":" 紫外火焰探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3448,"value":"66","label":" 红外火焰探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3449,"value":"67","label":" 感光火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3450,"value":"68","label":" 气体探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3451,"value":"69","label":" 图像摄像方式火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3452,"value":"70","label":" 感声火灾探测器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3453,"value":"71","label":" 气体灭火控制器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3454,"value":"72","label":" 消防电气控制装置","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3455,"value":"73","label":" 消防控制室图形显示装置","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3456,"value":"74","label":" 消防水泵","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3457,"value":"75","label":" 消防水箱","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3458,"value":"76","label":" 喷淋泵","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3459,"value":"77","label":" 水流指示器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3460,"value":"78","label":" 信号阀","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3461,"value":"79","label":" 报警阀","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3462,"value":"80","label":" 压力开关","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3463,"value":"81","label":" 阀驱动装置","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3464,"value":"82","label":" 防火门","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3465,"value":"83","label":" 防火阀","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3466,"value":"84","label":" 通风空调","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3467,"value":"85","label":" 泡沫液泵","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3468,"value":"86","label":" 管网电磁阀","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3469,"value":"87","label":" 防烟排烟风机","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3470,"value":"88","label":" 排烟防火阀","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3471,"value":"89","label":" 常闭送风口","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3472,"value":"90","label":" 排烟口","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3473,"value":"91","label":" 电控挡烟垂壁","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3474,"value":"92","label":" 防火卷帘控制器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3475,"value":"93","label":" 防火门监控器","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3476,"value":"94","label":" 警报装置","type":"device_type","parentId":"3260","level":"2","icon":null,"description":null},
// {"id":3492,"value":"95","label":"无线输出模块","type":"device_type","parentId":"3263","level":"2","icon":null,"description":null},
// {"id":3493,"value":"96","label":"无线输入模块","type":"device_type","parentId":"3263","level":"2","icon":null,"description":null},
// {"id":3494,"value":"97","label":"无线输入/输出模块","type":"device_type","parentId":"3263","level":"2","icon":null,"description":null},
// {"id":3495,"value":"98","label":"联动摄像头","type":"device_type","parentId":"3264","level":"2","icon":null,"description":null}],
// "total":100,"code":"0","msg":"成功","timestamp":1567590885089}