import request from '@/router/axios'
//警情处理/处理记录时
export function getWaringTree(query) {
    return request({
        url: '/unit/dict/typemore',
        method: 'get',
        params: query
    })
}
// 获取不同类型页面接口
export function searchTableList(query){
    return request({
        url:'/unit/monitorremotesystem/page',
        method:'get',
        params:query
    })
}

export function getEquipment(query){
    return request({
        url:'/unit/unitdevice/'+query,
        method:'get',
        // params:query
    })
}
//當前狀態
export function getMotesystem(query){
    return request({
        // url:'/unit/monitorremotesystem/deviceId',
        url:'/unit/monitorremotesystem/deviceId/' + query,
        method:'get',
        // params:query
    })
}

//获取警情信息
export function getUnitdeviceNew(query){
    // debugger;
    return request({
        url:'/unit/devicealertdeal/'+query,
        method:'get',
        // params:query
    })
}

//相關圖片
export function getUnitdevice(query){
    // debugger;
    return request({
        url:'/unit/unitdevice/deviceId/'+query,
        method:'get',
        // params:query
    })
}

//狀態記錄
export function getRecord(query){
    return request({
        url:'/unit/devicealertrecord/page',
        method:'get',
        params:query
    })
}

//状态分析
export function getAnaly(query){
    return request({
        // url:'/unit/analysisdeviceorgmonth/page',
        url:'/unit/analysisdeviceorgdaybydeviceid/page',
        method:'get',
        params:query
    })
}


//动态曲线模拟数据
export function dynamic(){
    return request({
        url:'./dynamic.json',
        method:'get',
        // params:query
    })
}

export const dialog = {
    "data": [
        {
            "id": "1ab03535-1eb5-4e70-b6be-c5a3dfdf39b5",
            "orgId": 1,
            "deviceId": "1901251401000001",
            "deviceName": null,
            "deviceModel": "1401",
            "deviceType": "27",
            "createTime": "2019-03-19T13:56:15",
            "warnList": 1,
            "controCmd": 17,
            "dataLen": 4,
            "dataCount": 1,
            "warnLevel": "1",
            "dealState": "0",
            "warnState": "1",
            "systemId": null,
            "buildingId": null,
            "floorId": null,
            "location": null,
            "warn01": 1,
            "warn02": 0,
            "warn03": 0,
            "warn04": 0,
            "warn05": 0,
            "warn06": 0,
            "warn07": 0,
            "warn08": 0,
            "warn09": 0,
            "warn10": 0,
            "warn11": 0,
            "warn12": 0,
            "warn13": 0,
            "warn14": 0,
            "warn15": 0,
            "warn16": 0,
            "warnConfirmType": null,
            "warnConfirmDes": null,
            "warnLocaleConfirmPhoto": null,
            "firstViewer": null,
            "firstViewTime": null,
            "warnConfirmor": null,
            "warnConfirmTime": null,
            "warnDealResultPhoto": null,
            "warnDealWay": null,
            "warnDealDes": null,
            "warnHandler": null,
            "dealTime": null,
            "detailData": "[{\"type\":24,\"len\":2,\"datas\":[1]}]"
        },
        {
            "id": "2895d160-8830-491d-be0b-45783d4a6bcc",
            "orgId": 1,
            "deviceId": "1609270501000001",
            "deviceName": null,
            "deviceModel": "0501",
            "deviceType": "26",
            "createTime": "2019-03-06T10:15:48",
            "warnList": 1,
            "controCmd": 17,
            "dataLen": 4,
            "dataCount": 1,
            "warnLevel": "1",
            "dealState": "0",
            "warnState": "1",
            "systemId": 11,
            "buildingId": 1,
            "floorId": 6,
            "location": null,
            "warn01": 1,
            "warn02": 0,
            "warn03": 0,
            "warn04": 0,
            "warn05": 0,
            "warn06": 0,
            "warn07": 0,
            "warn08": 0,
            "warn09": 0,
            "warn10": 0,
            "warn11": 0,
            "warn12": 0,
            "warn13": 0,
            "warn14": 0,
            "warn15": 0,
            "warn16": 0,
            "warnConfirmType": null,
            "warnConfirmDes": null,
            "warnLocaleConfirmPhoto": null,
            "firstViewer": null,
            "firstViewTime": null,
            "warnConfirmor": null,
            "warnConfirmTime": null,
            "warnDealResultPhoto": null,
            "warnDealWay": null,
            "warnDealDes": null,
            "warnHandler": null,
            "dealTime": null,
            "detailData": "[{\"type\":6,\"len\":2,\"datas\":[1]}]"
        },
        {
            "id": "28deddb5-1b6c-4be3-8ffc-500875f54bc1",
            "orgId": 1,
            "deviceId": "1903150101000001",
            "deviceName": null,
            "deviceModel": "0101",
            "deviceType": "43",
            "createTime": "2019-03-19T17:23:13",
            "warnList": 7,
            "controCmd": 17,
            "dataLen": 48,
            "dataCount": 8,
            "warnLevel": "1",
            "dealState": "0",
            "warnState": "1",
            "systemId": null,
            "buildingId": null,
            "floorId": null,
            "location": null,
            "warn01": 1,
            "warn02": 1,
            "warn03": 1,
            "warn04": 0,
            "warn05": 0,
            "warn06": 0,
            "warn07": 0,
            "warn08": 0,
            "warn09": 0,
            "warn10": 0,
            "warn11": 0,
            "warn12": 0,
            "warn13": 0,
            "warn14": 0,
            "warn15": 0,
            "warn16": 0,
            "warnConfirmType": null,
            "warnConfirmDes": null,
            "warnLocaleConfirmPhoto": null,
            "firstViewer": null,
            "firstViewTime": null,
            "warnConfirmor": null,
            "warnConfirmTime": null,
            "warnDealResultPhoto": null,
            "warnDealWay": null,
            "warnDealDes": null,
            "warnHandler": null,
            "dealTime": null,
            "detailData": "[{\"type\":3,\"len\":6,\"datas\":[0,0,0]},{\"type\":131,\"len\":4,\"datas\":[248,187]},{\"type\":4,\"len\":6,\"datas\":[0,0,0]},{\"type\":132,\"len\":2,\"datas\":[120]},{\"type\":1,\"len\":2,\"datas\":[0]},{\"type\":129,\"len\":2,\"datas\":[516]},{\"type\":2,\"len\":8,\"datas\":[0,0,0,0]},{\"type\":130,\"len\":2,\"datas\":[100]}]"
        },
        {
            "id": "34fb257e-ed27-4de2-83af-561297dafb8b",
            "orgId": 1,
            "deviceId": "1901251401000001",
            "deviceName": null,
            "deviceModel": "1401",
            "deviceType": "28",
            "createTime": "2019-03-18T13:53:49",
            "warnList": 1,
            "controCmd": 17,
            "dataLen": 4,
            "dataCount": 1,
            "warnLevel": "0",
            "dealState": "0",
            "warnState": "0",
            "systemId": null,
            "buildingId": null,
            "floorId": null,
            "location": null,
            "warn01": 1,
            "warn02": 0,
            "warn03": 0,
            "warn04": 0,
            "warn05": 0,
            "warn06": 0,
            "warn07": 0,
            "warn08": 0,
            "warn09": 0,
            "warn10": 0,
            "warn11": 0,
            "warn12": 0,
            "warn13": 0,
            "warn14": 0,
            "warn15": 0,
            "warn16": 0,
            "warnConfirmType": null,
            "warnConfirmDes": null,
            "warnLocaleConfirmPhoto": null,
            "firstViewer": null,
            "firstViewTime": null,
            "warnConfirmor": null,
            "warnConfirmTime": null,
            "warnDealResultPhoto": null,
            "warnDealWay": null,
            "warnDealDes": null,
            "warnHandler": null,
            "dealTime": null,
            "detailData": "[{\"type\":24,\"len\":2,\"datas\":[1]}]"
        },
        {
            "id": "3d950c4b-a8d9-4d72-a8f8-05fd4d18cec3",
            "orgId": 1,
            "deviceId": "1901251401000002",
            "deviceName": null,
            "deviceModel": "1401",
            "deviceType": "27",
            "createTime": "2019-03-18T13:53:56",
            "warnList": 1,
            "controCmd": 17,
            "dataLen": 4,
            "dataCount": 1,
            "warnLevel": "1",
            "dealState": "0",
            "warnState": "1",
            "systemId": null,
            "buildingId": null,
            "floorId": null,
            "location": null,
            "warn01": 1,
            "warn02": 0,
            "warn03": 0,
            "warn04": 0,
            "warn05": 0,
            "warn06": 0,
            "warn07": 0,
            "warn08": 0,
            "warn09": 0,
            "warn10": 0,
            "warn11": 0,
            "warn12": 0,
            "warn13": 0,
            "warn14": 0,
            "warn15": 0,
            "warn16": 0,
            "warnConfirmType": null,
            "warnConfirmDes": null,
            "warnLocaleConfirmPhoto": null,
            "firstViewer": null,
            "firstViewTime": null,
            "warnConfirmor": null,
            "warnConfirmTime": null,
            "warnDealResultPhoto": null,
            "warnDealWay": null,
            "warnDealDes": null,
            "warnHandler": null,
            "dealTime": null,
            "detailData": "[{\"type\":24,\"len\":2,\"datas\":[1]}]"
        },
        {
            "id": "4359dec0-3b05-423d-b13d-35e5dfe5767a",
            "orgId": 1,
            "deviceId": "1609270501000004",
            "deviceName": null,
            "deviceModel": "0501",
            "deviceType": "26",
            "createTime": "2019-03-08T10:17:23",
            "warnList": 1,
            "controCmd": 17,
            "dataLen": 4,
            "dataCount": 1,
            "warnLevel": "1",
            "dealState": "0",
            "warnState": "1",
            "systemId": 6,
            "buildingId": 2,
            "floorId": 7,
            "location": null,
            "warn01": 1,
            "warn02": 0,
            "warn03": 0,
            "warn04": 0,
            "warn05": 0,
            "warn06": 0,
            "warn07": 0,
            "warn08": 0,
            "warn09": 0,
            "warn10": 0,
            "warn11": 0,
            "warn12": 0,
            "warn13": 0,
            "warn14": 0,
            "warn15": 0,
            "warn16": 0,
            "warnConfirmType": null,
            "warnConfirmDes": null,
            "warnLocaleConfirmPhoto": null,
            "firstViewer": null,
            "firstViewTime": null,
            "warnConfirmor": null,
            "warnConfirmTime": null,
            "warnDealResultPhoto": null,
            "warnDealWay": null,
            "warnDealDes": null,
            "warnHandler": null,
            "dealTime": null,
            "detailData": "[{\"type\":6,\"len\":2,\"datas\":[1]}]"
        },
        {
            "id": "5e50dde7-9f33-45ae-af40-4580fffdf31a",
            "orgId": 1,
            "deviceId": "1901251401000003",
            "deviceName": null,
            "deviceModel": "1401",
            "deviceType": "27",
            "createTime": "2019-03-19T13:56:10",
            "warnList": 1,
            "controCmd": 17,
            "dataLen": 4,
            "dataCount": 1,
            "warnLevel": "1",
            "dealState": "0",
            "warnState": "1",
            "systemId": null,
            "buildingId": null,
            "floorId": null,
            "location": null,
            "warn01": 1,
            "warn02": 0,
            "warn03": 0,
            "warn04": 0,
            "warn05": 0,
            "warn06": 0,
            "warn07": 0,
            "warn08": 0,
            "warn09": 0,
            "warn10": 0,
            "warn11": 0,
            "warn12": 0,
            "warn13": 0,
            "warn14": 0,
            "warn15": 0,
            "warn16": 0,
            "warnConfirmType": null,
            "warnConfirmDes": null,
            "warnLocaleConfirmPhoto": null,
            "firstViewer": null,
            "firstViewTime": null,
            "warnConfirmor": null,
            "warnConfirmTime": null,
            "warnDealResultPhoto": null,
            "warnDealWay": null,
            "warnDealDes": null,
            "warnHandler": null,
            "dealTime": null,
            "detailData": "[{\"type\":24,\"len\":2,\"datas\":[1]}]"
        },
        {
            "id": "628c2dcf-8940-4d47-b90c-1bbb0681b52b",
            "orgId": 1,
            "deviceId": "1901251401000002",
            "deviceName": null,
            "deviceModel": "1401",
            "deviceType": "27",
            "createTime": "2019-03-19T13:56:13",
            "warnList": 1,
            "controCmd": 17,
            "dataLen": 4,
            "dataCount": 1,
            "warnLevel": "1",
            "dealState": "0",
            "warnState": "1",
            "systemId": null,
            "buildingId": null,
            "floorId": null,
            "location": null,
            "warn01": 1,
            "warn02": 0,
            "warn03": 0,
            "warn04": 0,
            "warn05": 0,
            "warn06": 0,
            "warn07": 0,
            "warn08": 0,
            "warn09": 0,
            "warn10": 0,
            "warn11": 0,
            "warn12": 0,
            "warn13": 0,
            "warn14": 0,
            "warn15": 0,
            "warn16": 0,
            "warnConfirmType": null,
            "warnConfirmDes": null,
            "warnLocaleConfirmPhoto": null,
            "firstViewer": null,
            "firstViewTime": null,
            "warnConfirmor": null,
            "warnConfirmTime": null,
            "warnDealResultPhoto": null,
            "warnDealWay": null,
            "warnDealDes": null,
            "warnHandler": null,
            "dealTime": null,
            "detailData": "[{\"type\":24,\"len\":2,\"datas\":[1]}]"
        },
        {
            "id": "735bae29-a75d-4dde-93a7-22f3a216333e",
            "orgId": 1,
            "deviceId": "1903150101000001",
            "deviceName": null,
            "deviceModel": "0101",
            "deviceType": "43",
            "createTime": "2019-03-19T17:23:16",
            "warnList": 7,
            "controCmd": 17,
            "dataLen": 48,
            "dataCount": 8,
            "warnLevel": "1",
            "dealState": "0",
            "warnState": "1",
            "systemId": null,
            "buildingId": null,
            "floorId": null,
            "location": null,
            "warn01": 1,
            "warn02": 1,
            "warn03": 1,
            "warn04": 0,
            "warn05": 0,
            "warn06": 0,
            "warn07": 0,
            "warn08": 0,
            "warn09": 0,
            "warn10": 0,
            "warn11": 0,
            "warn12": 0,
            "warn13": 0,
            "warn14": 0,
            "warn15": 0,
            "warn16": 0,
            "warnConfirmType": null,
            "warnConfirmDes": null,
            "warnLocaleConfirmPhoto": null,
            "firstViewer": null,
            "firstViewTime": null,
            "warnConfirmor": null,
            "warnConfirmTime": null,
            "warnDealResultPhoto": null,
            "warnDealWay": null,
            "warnDealDes": null,
            "warnHandler": null,
            "dealTime": null,
            "detailData": "[{\"type\":3,\"len\":6,\"datas\":[0,0,0]},{\"type\":131,\"len\":4,\"datas\":[248,187]},{\"type\":4,\"len\":6,\"datas\":[0,0,0]},{\"type\":132,\"len\":2,\"datas\":[120]},{\"type\":1,\"len\":2,\"datas\":[0]},{\"type\":129,\"len\":2,\"datas\":[516]},{\"type\":2,\"len\":8,\"datas\":[0,0,0,0]},{\"type\":130,\"len\":2,\"datas\":[100]}]"
        },
        {
            "id": "952f867b-42ab-4c15-aa8b-b80a83942da6",
            "orgId": 1,
            "deviceId": "1903150101000003",
            "deviceName": null,
            "deviceModel": "0101",
            "deviceType": "42",
            "createTime": "2019-03-19T17:22:59",
            "warnList": 7,
            "controCmd": 17,
            "dataLen": 48,
            "dataCount": 8,
            "warnLevel": "1",
            "dealState": "0",
            "warnState": "1",
            "systemId": null,
            "buildingId": null,
            "floorId": null,
            "location": null,
            "warn01": 1,
            "warn02": 1,
            "warn03": 1,
            "warn04": 0,
            "warn05": 0,
            "warn06": 0,
            "warn07": 0,
            "warn08": 0,
            "warn09": 0,
            "warn10": 0,
            "warn11": 0,
            "warn12": 0,
            "warn13": 0,
            "warn14": 0,
            "warn15": 0,
            "warn16": 0,
            "warnConfirmType": null,
            "warnConfirmDes": null,
            "warnLocaleConfirmPhoto": null,
            "firstViewer": null,
            "firstViewTime": null,
            "warnConfirmor": null,
            "warnConfirmTime": null,
            "warnDealResultPhoto": null,
            "warnDealWay": null,
            "warnDealDes": null,
            "warnHandler": null,
            "dealTime": null,
            "detailData": "[{\"type\":3,\"len\":6,\"datas\":[0,152,0]},{\"type\":131,\"len\":4,\"datas\":[248,187]},{\"type\":4,\"len\":6,\"datas\":[0,0,0]},{\"type\":132,\"len\":2,\"datas\":[120]},{\"type\":1,\"len\":2,\"datas\":[0]},{\"type\":129,\"len\":2,\"datas\":[1000]},{\"type\":2,\"len\":8,\"datas\":[18,18,18,18]},{\"type\":130,\"len\":2,\"datas\":[100]}]"
        },
        {
            "id": "a3b6d149-5973-4a92-8d2b-11ad31da33bb",
            "orgId": 1,
            "deviceId": "1901251401000003",
            "deviceName": null,
            "deviceModel": "1401",
            "deviceType": "27",
            "createTime": "2019-03-18T13:54:00",
            "warnList": 1,
            "controCmd": 17,
            "dataLen": 4,
            "dataCount": 1,
            "warnLevel": "1",
            "dealState": "0",
            "warnState": "1",
            "systemId": null,
            "buildingId": null,
            "floorId": null,
            "location": null,
            "warn01": 1,
            "warn02": 0,
            "warn03": 0,
            "warn04": 0,
            "warn05": 0,
            "warn06": 0,
            "warn07": 0,
            "warn08": 0,
            "warn09": 0,
            "warn10": 0,
            "warn11": 0,
            "warn12": 0,
            "warn13": 0,
            "warn14": 0,
            "warn15": 0,
            "warn16": 0,
            "warnConfirmType": null,
            "warnConfirmDes": null,
            "warnLocaleConfirmPhoto": null,
            "firstViewer": null,
            "firstViewTime": null,
            "warnConfirmor": null,
            "warnConfirmTime": null,
            "warnDealResultPhoto": null,
            "warnDealWay": null,
            "warnDealDes": null,
            "warnHandler": null,
            "dealTime": null,
            "detailData": "[{\"type\":24,\"len\":2,\"datas\":[1]}]"
        },
        {
            "id": "aec822d9-a653-4720-b1db-32fd8272880a",
            "orgId": 1,
            "deviceId": "1903150101000003",
            "deviceName": null,
            "deviceModel": "0101",
            "deviceType": "43",
            "createTime": "2019-03-19T17:23:10",
            "warnList": 7,
            "controCmd": 17,
            "dataLen": 48,
            "dataCount": 8,
            "warnLevel": "1",
            "dealState": "0",
            "warnState": "1",
            "systemId": null,
            "buildingId": null,
            "floorId": null,
            "location": null,
            "warn01": 1,
            "warn02": 1,
            "warn03": 1,
            "warn04": 0,
            "warn05": 0,
            "warn06": 0,
            "warn07": 0,
            "warn08": 0,
            "warn09": 0,
            "warn10": 0,
            "warn11": 0,
            "warn12": 0,
            "warn13": 0,
            "warn14": 0,
            "warn15": 0,
            "warn16": 0,
            "warnConfirmType": null,
            "warnConfirmDes": null,
            "warnLocaleConfirmPhoto": null,
            "firstViewer": null,
            "firstViewTime": null,
            "warnConfirmor": null,
            "warnConfirmTime": null,
            "warnDealResultPhoto": null,
            "warnDealWay": null,
            "warnDealDes": null,
            "warnHandler": null,
            "dealTime": null,
            "detailData": "[{\"type\":3,\"len\":6,\"datas\":[0,0,83]},{\"type\":131,\"len\":4,\"datas\":[248,187]},{\"type\":4,\"len\":6,\"datas\":[0,0,0]},{\"type\":132,\"len\":2,\"datas\":[120]},{\"type\":1,\"len\":2,\"datas\":[0]},{\"type\":129,\"len\":2,\"datas\":[1000]},{\"type\":2,\"len\":8,\"datas\":[18,18,18,18]},{\"type\":130,\"len\":2,\"datas\":[100]}]"
        }
    ]
}